dataset:
  train_start_year: 2001
  train_end_year: 2015
  test_year: 2016
  in_len: 12
  out_len: 12
  batch_size: 4
  num_workers: 4

model:
  name: "convlstm"
  input_shape: [12, 1, 128, 128]
  target_shape: [12, 1, 128, 128]
  num_layers: 4
  num_hidden: [64, 64, 64, 64]
  kernel_size: 3
  stride: 1
  padding: 1

trainer:
  check_val_every_n_epoch: 1
  precision: 16
  max_epochs: 50 
  accelerator: "gpu"
  devices: 1

optim:
  total_batch_size: 4
  max_epochs: 100
  lr: 0.001
  warmup_percentage: 0.1
  save_top_k: 3

distill:
  teacher_ckpt_path: "sst_colab_run_1/checkpoints/last.ckpt"
  teacher_cfg_path: "sst.yaml"
  loss_weight_enc: 1.0
  loss_weight_dec: 1.0
  loss_weight_output: 0.5

logging:
  monitor_lr: True
  logger_type: "tensorboard"
